// Package main is the entry point for the Naratel Box API.
//
// @title          Naratel Box API
// @version        1.0
// @description    Block-level deduplicated file storage with JWT authentication and QNAP S3 backend.
// @termsOfService http://naratel.id/terms
//
// @contact.name   Naratel Dev Team
// @contact.email  dev@naratel.id
//
// @license.name   MIT
// @license.url    https://opensource.org/licenses/MIT
//
// @host      localhost:8080
// @BasePath  /api/v1
//
// @securityDefinitions.apikey BearerAuth
// @in                         header
// @name                       Authorization
// @description                Enter: Bearer <your_jwt_token>
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	fiberlog "github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"

	"github.com/naratel/naratel-box/backend/internal/auth"
	"github.com/naratel/naratel-box/backend/internal/block"
	"github.com/naratel/naratel-box/backend/internal/config"
	"github.com/naratel/naratel-box/backend/internal/handler"
	"github.com/naratel/naratel-box/backend/internal/repository"
	"github.com/naratel/naratel-box/backend/internal/storage"

	_ "github.com/naratel/naratel-box/backend/docs" // generated by swag
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

func main() {
	// ── Config ────────────────────────────────────────────────────────────────
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config.Load: %v", err)
	}

	// ── Database ──────────────────────────────────────────────────────────────
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	pool, err := repository.NewPool(ctx, cfg.DSN())
	if err != nil {
		log.Fatalf("database connection failed: %v", err)
	}
	defer pool.Close()
	log.Println("✅ Database connected")

	// ── S3 Client ─────────────────────────────────────────────────────────────
	s3Client, err := storage.NewS3Client(
		cfg.S3Endpoint,
		cfg.S3AccessKey,
		cfg.S3SecretKey,
		cfg.S3Region,
		cfg.S3Bucket,
		cfg.S3ForcePathStyle,
	)
	if err != nil {
		log.Fatalf("S3 client init failed: %v", err)
	}
	log.Println("✅ S3 client ready")

	// ── Repositories ──────────────────────────────────────────────────────────
	userRepo  := repository.NewUserRepository(pool)
	blockRepo := repository.NewBlockRepository(pool)
	fileRepo  := repository.NewFileRepository(pool)

	// ── Block Processor ───────────────────────────────────────────────────────
	processor := block.NewProcessor(cfg.BlockSizeBytes(), blockRepo, s3Client)

	// ── Handlers ──────────────────────────────────────────────────────────────
	authHandler     := handler.NewAuthHandler(userRepo, cfg.JWTSecret, cfg.JWTExpiryHours)
	uploadHandler   := handler.NewUploadHandler(fileRepo, processor)
	downloadHandler := handler.NewDownloadHandler(fileRepo, blockRepo, s3Client)

	// ── Fiber App ─────────────────────────────────────────────────────────────
	app := fiber.New(fiber.Config{
		AppName:   "Naratel Box API",
		BodyLimit: 512 * 1024 * 1024, // 512 MB max upload body
	})

	// Global middleware
	app.Use(recover.New())
	app.Use(fiberlog.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept, Authorization",
		AllowMethods: "GET, POST, DELETE, OPTIONS",
	}))

	// ── Routes ────────────────────────────────────────────────────────────────
	api := app.Group("/api/v1")

	// Public
	authGroup := api.Group("/auth")
	authGroup.Post("/register", authHandler.Register)
	authGroup.Post("/login", authHandler.Login)

	// Protected (JWT required)
	files := api.Group("/files", auth.Middleware(cfg.JWTSecret))
	files.Post("/", uploadHandler.Upload)
	files.Get("/", uploadHandler.ListFiles)
	files.Get("/:id", downloadHandler.Download)
	files.Delete("/:id", downloadHandler.DeleteFile)

	// Health check
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	// Swagger UI — available at http://localhost:8080/swagger/index.html
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	// ── Graceful Shutdown ─────────────────────────────────────────────────────
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		addr := fmt.Sprintf(":%s", cfg.AppPort)
		log.Printf("🚀 Naratel Box API running on http://localhost%s", addr)
		if err := app.Listen(addr); err != nil {
			log.Fatalf("server error: %v", err)
		}
	}()

	<-quit
	log.Println("⏳ Shutting down gracefully...")
	if err := app.ShutdownWithTimeout(5 * time.Second); err != nil {
		log.Printf("shutdown error: %v", err)
	}
	log.Println("👋 Server stopped")
}
